platform :ios, '14.0'

target 'CerdAR' do
  use_frameworks!

  pod 'GoogleSignIn','6.2.3'
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'XMLCoder', '~> 0.12.0'

  target 'CerdARTests' do
    inherit! :search_paths
  end

  target 'CerdARUITests' do
  end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end

