# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CerdAR' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CerdAR
  pod 'GoogleSignIn'
  pod 'Mapbox-iOS-SDK', '~> 6.3.0'
  pod 'XMLCoder', '~> 0.12.0'
  target 'CerdARTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CerdARUITests' do
    # Pods for testing
  end

end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        # iOSのターゲットバージョンを14.0に引き上げ
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
        
        # 外部ライブラリの署名エラーを回避（追加部分）
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
      end
    end
  end
end
